// <auto-generated />
using System;
using FeedbackWebsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FeedbackWebsite.Migrations
{
    [DbContext(typeof(FeedbackWebsiteContext))]
    partial class FeedbackWebsiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FeedbackWebsite.Models.EventInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department");

                    b.Property<string>("EmployeeName");

                    b.Property<DateTime>("EventEndDate");

                    b.Property<string>("EventLocation");

                    b.Property<string>("EventName");

                    b.Property<string>("EventOrg");

                    b.Property<DateTime>("EventStartDate");

                    b.Property<string>("Position");

                    b.Property<string>("PresentersName");

                    b.HasKey("Id");

                    b.ToTable("EventInfoModel");
                });

            modelBuilder.Entity("FeedbackWebsite.Models.QuestionsInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<string>("Question1");

                    b.Property<string>("Question2");

                    b.Property<string>("Question3");

                    b.Property<string>("Question4");

                    b.Property<string>("Question5");

                    b.Property<string>("Question6");

                    b.Property<string>("Question7");

                    b.Property<string>("Question8");

                    b.Property<string>("Question9");

                    b.HasKey("Id");

                    b.ToTable("QuestionsInfoModel");
                });
#pragma warning restore 612, 618
        }
    }
}
